
/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package contextReceiversLib

// !LANGUAGE: +ContextReceivers
class LibraryClassOne {

    context(Comparator<T>)
            fun <T> T.compareTo(other: T) = compare(this, other)

    fun test() {
        println("42")
    }
}