/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package contextReceiversLib

class LibraryClassThree {
    // !LANGUAGE: +ContextReceivers
    class A {
        fun h1() {}
    }

    class B {
        fun h2() {}
    }

    context(A)
    fun B.bar() {
        h1()
        h2()
    }
}